### ISSUE TITLE
Template should be webpackable

### ISSUE THREAD

**Issue by radeva** [NativeScript/template-enterprise-auth-ng#11]
Valid for all templates

**Comment by zbranzov** [comment]
- tns run android --bundle --env.uglify --env.snapshot --env.aot => Fails
- tns run ios --bundle --env.uglify --env.aot => Fails

**Comment by radeva** [comment]
It was on PR. It's now merged

**Comment by zbranzov** [comment]
Testes with the merged code and commands above build fails because of not initialized Kinvey
