### ISSUE TITLE
Unable to run app on physical iOS devices

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/template-enterprise-auth-ng#14]
Hey all,

I’m running into errors when trying to deploy this template to physical iOS devices. (I have no problems on the iOS simulator.)

To recreate all you have to do is...

```
tns create my-app-name --template tns-template-enterprise-auth-ng
cd my app-name
tns run ios
```

I get the following error.

```
Xcode build...
2018-03-22 13:15:40.858 xcodebuild[27311:925407]  DTDeviceKit: deviceType from 17f283cfaacab97e1e20994d4b8cd9ffc2a4dbcb was NULL
```

I’ve tried on an iPhone 6, an iPhone X, and an iPad Pro and I get the same error on all of them. I have no problems deploying an app created using `tns create my-app-name --ng` to those same devices.

I’m finding this very odd because I’m really not sure what it is about this app that would create this problem. Any help would be greatly appreciated.

Thanks.

**Comment by tjvantoll** [comment]
Here’s a log of my trying to run the app with `tns run ios --log trace`: https://gist.github.com/tjvantoll/fd9bc7c0f3b4ea46b6b76042c4311479.

I also threw the full app I’m working on up on GitHub: https://github.com/tjvantoll/mobile. I might have something weird with my setup, because I’m also having issues with LiveSync as well. (LiveSync is triggering a full iOS build with every small change.)

Any help would be appreciated. I’ll reach out tomorrow.

**Comment by rosen-vladimirov** [comment]
Hey @tjvantoll ,
Thank you for providing the logs. Unfortunately they do not contain the error - it looks like the device has been detached from your machine during the last step of building the application. Can you verify your cable is working correctly, and ensure the device is attached during the full process of building and running the application.

**Comment by tjvantoll** [comment]
The error definitely looks like I detached the device, but I’m 100% positive that it was attached the whole time. I’ll try again with a different cord to verify my sanity.

**Comment by tjvantoll** [comment]
I am able to deploy the app through Xcode to my device with no issues. This is odd. I will do some more digging tomorrow.

**Comment by zbranzov** [comment]
I was able to reproduce it. It seems the build hangs there and if you wait a few more minutes it will continue as far as I can remember

**Comment by tjvantoll** [comment]
@zbranzov Glad I’m not the only one to hit this :)

I am a little confused though, are you saying that if you wait long enough the build will succeed and push the app out?

**Comment by tjvantoll** [comment]
Oh wow, you’re totally right @zbranzov. The deploy eventually works but it hangs for something like 3–4 minutes 😮 

Anybody have any clue why this happens? I gave up on the build because I thought it was stuck, and I’m guessing some of our users will do the same.

Another potentially related problem—after I deploy the app to my device the CLI watcher immediately crashes with following error. Not sure what’s up, but between these two problems it’s currently impossible for me to develop apps using this template on USB-connected iOS devices, and any help figuring out what’s up here would be appreciated.

```
CONSOLE LOG: ANGULAR BOOTSTRAP DONE. 2069.216
CONSOLE LOG file:///app/tns_modules/tns-core-modules/profiling/profiling.js:10:16: ANGULAR BOOTSTRAP DONE. 2069.216
Loaded MobileCoreServices.framework
Faulting in NSHTTPCookieStorage singleton
Faulting in CFHTTPCookieStorage singleton
Creating default cookie storage with default identifier
TIC Enabling TLS [1:0x1d0167500]
TIC TCP Conn Start [1:0x1d0167500]
Task <ED581DA5-F334-4034-818D-D9E36D32ABB4>.<1> setting up Connection 1
TIC TLS Event [1:0x1d0167500]: 1, Pending(0)
TIC TLS Event [1:0x1d0167500]: 2, Pending(0)
TIC TLS Event [1:0x1d0167500]: 11, Pending(0)
TIC TLS Event [1:0x1d0167500]: 12, Pending(0)
TIC TLS Event [1:0x1d0167500]: 14, Pending(0)
System Trust Evaluation yielded status(0)
TIC TLS Trust Result [1:0x1d0167500]: 0
TIC TLS Event [1:0x1d0167500]: 20, Pending(0)
TIC TCP Conn Connected [1:0x1d0167500]: Err(16)
TIC TCP Conn Event [1:0x1d0167500]: 1
TIC TCP Conn Event [1:0x1d0167500]: 8
TIC TLS Handshake Complete [1:0x1d0167500]
Task <ED581DA5-F334-4034-818D-D9E36D32ABB4>.<1> now using Connection 1
Task <ED581DA5-F334-4034-818D-D9E36D32ABB4>.<1> sent request, body S
Executing after-watch hook from /Users/tj/Desktop/ProgressDemo/mobile/hooks/after-watch/nativescript-dev-typescript.js
Stopping tsc watch
TypeScript compiler failed with exit code null
```

**Comment by tjvantoll** [comment]
I’m going to close this. The LiveSync issues were my own fault, and apps I build using this template are consistently deploying, albeit with a big delay.

At some point we might want to look at why apps built with this template take so long to deploy (I just timed my `tns run ios` at over 5 minutes), but I don’t believe there’s an actual error so I’ll close this.
