### ISSUE TITLE
Margin issues on Nexus 5

### ISSUE THREAD

**Issue by radeva** [NativeScript/template-enterprise-auth-ng#8]
See https://www.screencast.com/t/qvlFSJLQK7Q9 .
Reproduced on Nexus 5, API 23, 24, 26.

Valid for ALL flavors

**Comment by zbranzov** [comment]
- login page text is shrinked https://screencast.com/t/9CC7ApoFt57

**Comment by radeva** [comment]
The first 2 are caused by the small screen of the emulator. NativeScript currently doesn't support @media queries so there are no many options to do in this case.

Regarding the 3d one, it's reported to Kinvey and is something the team on their side is going to improve.
